export const BOIL_CREATE_BOILER = 'BOIL_CREATE_BOILER';
export const BOIL_UPDATE_BOILER = 'BOIL_UPDATE_BOILER';
export const BOIL_DELETE_BOILER = 'BOIL_DELETE_BOILER';
export const BOIL_SET_ALL_BOILERS = 'BOIL_SET_ALL_BOILERS';
export const BOIL_SET_ERROR = 'BOIL_SET_ERROR';
export const BOIL_SET_LOADING_TRUE = 'BOIL_SET_LOADING_TRUE';
