export const CREATE_BOILER = 'CREATE_BOILER';
export const UPDATE_BOILER = 'UPDATE_BOILER';
export const DELETE_BOILER = 'DELETE_BOILER';
export const SET_ALL_BOILERS = 'SET_ALL_BOILERS';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
