export const BUILD_CREATE_BUILDING = 'BUILD_CREATE_BUILDING';
export const BUILD_UPDATE_BUILDING = 'BUILD_UPDATE_BUILDING';
export const BUILD_DELETE_BUILDING = 'BUILD_DELETE_BUILDING';
export const BUILD_SET_ALL_BUILDINGS = 'BUILD_SET_ALL_BUILDINGS';
export const BUILD_SET_ERROR = 'BUILD_SET_ERROR';
export const BUILD_SET_LOADING_TRUE = 'BUILD_SET_LOADING_TRUE';
