export const BUILD_CREATE_BUILDING = 'BUILD_CREATE_BUILDING';
export const BUILD_UPDATE_BUILDING = 'BUILD_UPDATE_BUILDING';
export const BUILD_DELETE_BUILDING = 'BUILD_DELETE_BUILDING';
export const BUILD_SET_ALL_BUILDINGS = 'BUILD_SET_ALL_BUILDINGS';

export const BUILD_SET_ERROR = 'BUILD_SET_ERROR';
export const BUILD_SET_LOADING_TRUE = 'BUILD_SET_LOADING_TRUE';

export const BUILD_SET_CREATE_ACTION = 'BUILD_SET_CREATE_ACTION';
export const BUILD_SET_UPDATE_ACTION = 'BUILD_SET_UPDATE_ACTION';
export const BUILD_SET_DELETE_ACTION = 'BUILD_SET_DELETE_ACTION';
export const BUILD_UNSET_ACTION = 'BUILD_UNSET_ACTION';
