export const CREATE_BUILDINGS = 'CREATE_BUILDINGS ';
export const UPDATE_BUILDINGS = 'UPDATE_BUILDINGS ';
export const DELETE_BUILDINGS = 'DELETE_BUILDINGS ';
export const SET_ALL_BUILDINGS = 'SET_ALL_BUILDINGS';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
