export const CREATE_TECHNICIAN = 'CREATE_TECHNICIAN';
export const UPDATE_TECHNICIAN = 'UPDATE_TECHNICIAN';
export const DELETE_TECHNICIAN = 'DELETE_TECHNICIAN';
export const SET_ALL_TECHNICIANS = 'SET_ALL_TECHNICIANS';
export const SET_ERROR = 'SET_ERROR';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';
