export const TECH_CREATE_TECHNICIAN = 'TECH_CREATE_TECHNICIAN';
export const TECH_UPDATE_TECHNICIAN = 'TECH_UPDATE_TECHNICIAN';
export const TECH_DELETE_TECHNICIAN = 'TECH_DELETE_TECHNICIAN';
export const TECH_SET_ALL_TECHNICIANS = 'TECH_SET_ALL_TECHNICIANS';
export const TECH_SET_ERROR = 'TECH_SET_ERROR';
export const TECH_SET_LOADING_TRUE = 'TECH_SET_LOADING_TRUE';
